development:
  GOOGLE_PLACES_API_KEY: ENV["GOOGLE_API_KEY"]
  FSQ_CLIENT_ID: ENV["FSQ_CLIENT_ID"]
  FSQ_CLIENT_SECRET: ENV["FSQ_CLIENT_SECRET"]
  YELP_CONSUMER_KEY: ENV["YELP_CONSUMER_KEY"]
  YELP_CONSUMER_SECRET: ENV["YELP_CONSUMER_SECRET"]
  YELP_TOKEN: ENV["YELP_TOKEN"]
  YELP_TOKEN_SECRET: ENV["YELP_TOKEN_SECRET"]

test:
  GOOGLE_PLACES_API_KEY: ENV["GOOGLE_API_KEY"]
  FSQ_CLIENT_ID: ENV["FSQ_CLIENT_ID"]
  FSQ_CLIENT_SECRET: ENV["FSQ_CLIENT_SECRET"]
  YELP_CONSUMER_KEY: ENV["YELP_CONSUMER_KEY"]
  YELP_CONSUMER_SECRET: ENV["YELP_CONSUMER_SECRET"]
  YELP_TOKEN: ENV["YELP_TOKEN"]
  YELP_TOKEN_SECRET: ENV["YELP_TOKEN_SECRET"]

production:
  GOOGLE_PLACES_API_KEY: ENV["GOOGLE_API_KEY"]
  FSQ_CLIENT_ID: ENV["FSQ_CLIENT_ID"]
  FSQ_CLIENT_SECRET: ENV["FSQ_CLIENT_SECRET"]
  YELP_CONSUMER_KEY: ENV["YELP_CONSUMER_KEY"]
  YELP_CONSUMER_SECRET: ENV["YELP_CONSUMER_SECRET"]
  YELP_TOKEN: ENV["YELP_TOKEN"]
  YELP_TOKEN_SECRET: ENV["YELP_TOKEN_SECRET"]
